markdown: rdiscount

lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink: date
url: http://gezhu.github.io
name: Gezhu
author: gezhu
#qq: 1135558183
email: zhulianuha121@qq.com
duoshuo: gezhu
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2067815867
github: gezhu
pygments: true
safe: true
paginate: 20
about: "攻城狮一头，目前从事Linux的相关运维。	
热爱Linux，开源爱好者，喜欢虚拟化，github等。		
电脑洁癖与性能癖。  	
偶尔微博，偶尔wow。"
